general:
  # pointsPerLevel - number of points needed to advance 1 island level.
  pointsPerLevel: 1000

  # default - the default value for blocks not listed in blockValues here.
  default: 10

  # diminishingReturns - the default value to use for diminishing returns. This is the number of blocks before DR starts to
  # lower value.
  # no-value or a value of 0 means disabled.
  # diminishingReturns: 5000

  # limit - the default hard-limit for blocks not mentioned. This is the number of blocks that can provide score.
  # no-value or -1 means disabled.
  # limit: 10000

  # blocks - the blocks listed below will have custom values instead of the default.
blocks:
  ACACIA_DOOR:
    score: 20.0
  ACACIA_FENCE:
    score: 17.5
    diminishingReturns: 5000
  ACACIA_FENCE_GATE:
    score: 40.0
    diminishingReturns: 100
  ACACIA_STAIRS:
    score: 15.0
  ACACIA_TRAPDOOR:
    score: 30.0
  ACACIA_WOOD:
    additionalBlocks:
      - STRIPPED_ACACIA_WOOD
    diminishingReturns: 10000
  ACTIVATOR_RAIL:
    score: 20.0
  AIR:
    score: 0.0
    limit: 0
  ANDESITE:
    score: 12.5
    diminishingReturns: 10000
  ANVIL:
    additionalBlocks:
    - CHIPPED_ANVIL
    - DAMAGED_ANVIL
    score: 150.0
    limit: 5
  BARRIER:
    score: 0.0
  BEACON:
    score: 2000.0
    limit: 10
    negativeReturns: 15
  BEDROCK:
    score: 0.0
  BIRCH_DOOR:
    score: 20.0
  BIRCH_FENCE:
    score: 17.5
    diminishingReturns: 5000
  BIRCH_FENCE_GATE:
    score: 40.0
    diminishingReturns: 100
  BIRCH_STAIRS:
    score: 15.0
  BIRCH_TRAPDOOR:
    score: 30.0
  BIRCH_WOOD:
    additionalBlocks:
      - STRIPPED_BIRCH_WOOD
    diminishingReturns: 10000
  BIRCH_WOOD_STAIRS:
    score: 15.0
  BOOKSHELF:
    score: 50.0
  BREWING_STAND:
    score: 30.0
    limit: 10
  BRICK:
    score: 50.0
  BRICK_SLAB:
    score: 25.0
    diminishingReturns: 10000
  BRICK_STAIRS:
    score: 75.0
    diminishingReturns: 5000
  BROWN_MUSHROOM:
    diminishingReturns: 100
  CACTUS:
    score: 0.0
  CAKE_BLOCK:
    score: 50.0
  CARPET:
    score: 20.0
    diminishingReturns: 5000
  CARROT:
    score: 0.0
  CAULDRON:
    score: 155.0
    limit: 10
  CHISELED_RED_SANDSTONE:
    score: 25.0
  CHISELED_SANDSTONE:
    score: 80.0
  CLAY:
    score: 50.0
  COAL_BLOCK:
    score: 500.0
    diminishingReturns: 100
  COAL_ORE:
    score: 200.0
  COARSE_DIRT:
    score: 25.0
    diminishingReturns: 10000
  COBBLESTONE:
    limit: 10000
  COBBLESTONE_SLAB:
    score: 5.0
    diminishingReturns: 10000
  COBBLESTONE_STAIRS:
    score: 15.0
    diminishingReturns: 5000
  COBBLE_WALL:
    diminishingReturns: 5000
  COCOA:
    score: 0.0
  COMMAND:
    score: 0.0
  CREEPER_HEAD:
    additionalBlocks:
      - CREEPER_HEAD
    score: 1000.0
  CRIMSON_DOOR:
    score: 20.0
  CRIMSON_STAIRS:
    score: 15.0
  CRIMSON_TRAPDOOR:
    score: 30.0
  CROPS:
    score: 0.0
  CUT_RED_SANDSTONE:
    score: 25.0
  CUT_RED_SANDSTONE_SLAB:
    score: 12.5
    diminishingReturns: 10000
  CUT_SANDSTONE:
    score: 80.0
  CUT_SANDSTONE_SLAB:
    score: 40.0
    diminishingReturns: 10000
  DARK_OAK_DOOR:
    score: 20.0
  DARK_OAK_FENCE:
    score: 17.5
    diminishingReturns: 5000
  DARK_OAK_FENCE_GATE:
    score: 40.0
    diminishingReturns: 100
  DARK_OAK_STAIRS:
    score: 15.0
  DARK_OAK_TRAPDOOR:
    score: 30.0
  DARK_OAK_WOOD:
    additionalBlocks:
      - STRIPPED_DARK_OAK_WOOD
    diminishingReturns: 10000
  DARK_PRISMARINE:
    score: 50.0
  DARK_PRISMARINE_SLAB:
    score: 25.0
  DAYLIGHT_DETECTOR:
    score: 200.0
  DAYLIGHT_DETECTOR_INVERTED:
    score: 200.0
  DETECTOR_RAIL:
    score: 20.0
  DIAMOND_BLOCK:
    score: 5000.0
  DIAMOND_ORE:
    score: 400.0
  DIORITE:
    score: 12.5
    diminishingReturns: 10000
  DIRT:
    score: 20.0
    diminishingReturns: 10000
  DRAGON_EGG:
    score: 5000.0
    limit: 2
  EMERALD_BLOCK:
    score: 1000.0
  EMERALD_ORE:
    score: 200.0
  ENCHANTMENT_TABLE:
    score: 150.0
  ENDER_CHEST:
    score: 2000.0
    limit: 3
  ENDER_PORTAL:
    score: 0.0
  ENDER_PORTAL_FRAME:
    score: 0.0
  ENDER_STONE:
    score: 15.0
    limit: 10000
  FENCE:
    score: 17.5
    diminishingReturns: 5000
  FENCE_GATE:
    score: 40.0
    diminishingReturns: 100
  FIRE:
    score: 0.0
  GLASS:
    score: 50.0
  GLOWSTONE:
    score: 20.0
  GOLD_BLOCK:
    score: 1500.0
    diminishingReturns: 100
  GOLD_ORE:
    score: 500.0
  GRANITE:
    score: 12.5
    diminishingReturns: 10000
  GRASS:
    score: 20.0
    diminishingReturns: 10000
  GRAVEL:
    score: 20.0
  HAY_BLOCK:
    score: 20.0
  HEAVY_WEIGHTED_PRESSURE_PLATE:
    score: 50.0
  HOPPER:
    score: 125.0
    limit: 10
    negativeReturns: 5
  HUGE_MUSHROOM_1:
    score: 100.0
    diminishingReturns: 30
  HUGE_MUSHROOM_2:
    score: 100.0
    diminishingReturns: 30
  ICE:
    score: 50.0
  IRON_BLOCK:
    score: 300.0
  IRON_DOOR_BLOCK:
    score: 200.0
  IRON_FENCE:
    score: 12.5
  IRON_ORE:
    score: 200.0
  IRON_TRAPDOOR:
    score: 20.0
    diminishingReturns: 10
  JACK_O_LANTERN:
    score: 20.0
  JUKEBOX:
    score: 50.0
  JUNGLE_DOOR:
    score: 20.0
  JUNGLE_FENCE:
    score: 17.5
    diminishingReturns: 5000
  JUNGLE_FENCE_GATE:
    score: 40.0
    diminishingReturns: 100
  JUNGLE_STAIRS:
    score: 15.0
  JUNGLE_TRAPDOOR:
    score: 30.0
  JUNGLE_WOOD:
    additionalBlocks:
      - STRIPPED_JUNGLE_WOOD
    diminishingReturns: 10000
  JUNGLE_WOOD_STAIRS:
    score: 15.0
  LADDER:
    score: 0.0
  LAPIS_BLOCK:
    score: 500.0
  LAPIS_ORE:
    score: 300.0
  LAVA:
    score: 0.0
  LIGHT_WEIGHTED_PRESSURE_PLATE:
    score: 115.0
  LOG/0-5:
    additionalBlocks:
    - LOG_2
    diminishingReturns: 100
  LOG_2:
    diminishingReturns: 100
  LOG_2/1:
    diminishingReturns: 100
  LONG_GRASS:
    diminishingReturns: 100
  MELON_BLOCK:
    score: 0.0
  MELON_STEM:
    score: 0.0
  MOSSY_COBBLESTONE:
    score: 30.0
  MYCEL:
    score: 20.0
    diminishingReturns: 10000
  NETHERRACK:
    limit: 10000
  NETHER_BRICK_SLAB:
    score: 10.0
    diminishingReturns: 20000
  NETHER_BRICK_FENCE:
    score: 30.0
    diminishingReturns: 10000
  NETHER_BRICKS:
    score: 20.0
    diminishingReturns: 20000
  NETHER_BRICK_STAIRS:
    score: 30.0
    diminishingReturns: 5000
  NETHER_FENCE:
    score: 60.0
    diminishingReturns: 5000
  NOTE_BLOCK:
    score: 20.0
  OAK_DOOR:
    score: 20.0
  OAK_LEAVES:
    additionalBlocks:
    - ACACIA_LEAVES
    - BIRCH_LEAVES
    - DARK_OAK_LEAVES
    - JUNGLE_LEAVES
    - SPRUCE_LEAVES
    score: 0.0
  OAK_LOG:
    additionalBlocks:
      - ACACIA_LOG
      - BIRCH_LOG
      - DARK_OAK_LOG
      - JUNGLE_LOG
      - SPRUCE_LOG
    diminishingReturns: 100
  OAK_PRESSURE_PLATE:
    additionalBlocks:
    - ACACIA_PRESSURE_PLATE
    - BIRCH_PRESSURE_PLATE
    - CRIMSON_PRESSURE_PLATE
    - DARK_OAK_PRESSURE_PLATE
    - JUNGLE_PRESSURE_PLATE
    - SPRUCE_PRESSURE_PLATE
    - WARPED_PRESSURE_PLATE
    score: 0.0
  OAK_SAPLING:
    additionalBlocks:
      - ACACIA_SAPLING
      - BIRCH_SAPLING
      - DARK_OAK_SAPLING
      - JUNGLE_SAPLING
      - SPRUCE_SAPLING
    score: 0.0
  OAK_SIGN:
    additionalBlocks:
      - ACACIA_SIGN
      - ACACIA_WALL_SIGN
      - BIRCH_SIGN
      - BIRCH_WALL_SIGN
      - CRIMSON_SIGN
      - CRIMSON_WALL_SIGN
      - DARK_OAK_SIGN
      - DARK_OAK_WALL_SIGN
      - JUNGLE_SIGN
      - JUNGLE_WALL_SIGN
      - OAK_WALL_SIGN
      - SPRUCE_SIGN
      - SPRUCE_WALL_SIGN
      - WARPED_SIGN
      - WARPED_WALL_SIGN
    score: 0.0
  OAK_SLAB:
    additionalBlocks:
      - ACACIA_SLAB
      - BIRCH_SLAB
      - CRIMSON_SLAB
      - DARK_OAK_SLAB
      - JUNGLE_SLAB
      - SPRUCE_SLAB
      - WARPED_SLAB
    score: 5.0
    diminishingReturns: 15000
  OAK_STAIRS:
    score: 15.0
  OAK_TRAPDOOR:
    score: 30.0
  OAK_WOOD:
    additionalBlocks:
      - STRIPPED_OAK_WOOD
    diminishingReturns: 10000
  OBSIDIAN:
    score: 200.0
    diminishingReturns: 50
  PACKED_ICE:
    score: 15.0
  PISTON_BASE:
    score: 40.0
  PISTON_EXTENSION:
    score: 0.0
  PISTON_MOVING_PIECE:
    score: 0.0
  PISTON_STICKY_BASE:
    score: 60.0
  PLAYER_HEAD:
    additionalBlocks:
      - PLAYER_WALL_HEAD
    score: 1000.0
  PODZOL:
    score: 25.0
    diminishingReturns: 10000
  POLISHED_ANDESITE:
    score: 15.0
    diminishingReturns: 10000
  POLISHED_DIORITE:
    score: 15.0
    diminishingReturns: 10000
  POLISHED_GRANITE:
    score: 15.0
    diminishingReturns: 10000
  PORTAL:
    score: 0.0
  POTATO:
    score: 0.0
  POWERED_RAIL:
    score: 20.0
  PRISMARINE:
    score: 50.0
  PRISMARINE_SLAB:
    score: 25.0
  PRISMARINE_BRICKS:
    score: 50.0
  PRISMARINE_BRICK_SLAB:
    score: 25.0
  PUMPKIN_STEM:
    score: 0.0
  QUARTZ_BLOCK:
    additionalBlocks:
      - CHISELED_QUARTZ_BLOCK
      - QUARTZ_BRICKS
      - QUARTZ_PILLAR
    score: 100.0
    diminishingReturns: 5000
  QUARTZ_ORE:
    score: 50.0
  QUARTZ_SLAB:
    score: 50.0
    diminishingReturns: 10000
  QUARTZ_STAIRS:
    score: 150.0
    diminishingReturns: 5000
  REDSTONE_BLOCK:
    score: 150.0
  REDSTONE_LAMP_OFF:
    score: 20.0
  REDSTONE_LAMP_ON:
    score: 20.0
  REDSTONE_WIRE:
    score: 0.0
  RED_MUSHROOM:
    diminishingReturns: 100
  RED_ROSE:
    diminishingReturns: 100
  RED_SAND:
    score: 22.5
    diminishingReturns: 10000
  RED_SANDSTONE:
    score: 25.0
  RED_SANDSTONE_SLAB:
    score: 12.5
    diminishingReturns: 10000
  RED_SANDSTONE_STAIRS:
    score: 20.0
  SAND:
    score: 20.0
    diminishingReturns: 10000
  SANDSTONE:
    score: 80.0
  SANDSTONE_SLAB:
    score: 40.0
    diminishingReturns: 10000
  SANDSTONE_STAIRS:
    score: 120.0
    diminishingReturns: 5000
  SEA_LANTERN:
    score: 50.0
  SKELETON_SKULL:
    additionalBlocks:
      - SKELETON_WALL_SKULL
    score: 1000.0
  SLIME_BLOCK:
    score: 250.0
    diminishingReturns: 100
  SMOOTH_BRICK:
    score: 12.0
    diminishingReturns: 20000
  SMOOTH_RED_SANDSTONE:
    score: 25.0
  SMOOTH_RED_SANDSTONE_SLAB:
    score: 12.5
    diminishingReturns: 10000
  SMOOTH_SANDSTONE:
    score: 80.0
  SMOOTH_SANDSTONE_SLAB:
    score: 40.0
    diminishingReturns: 10000
  SMOOTH_STAIRS:
    score: 20.0
    diminishingReturns: 5000
  SNOW:
    score: 0.0
  SNOW_BLOCK:
    score: 50.0
  SOIL:
    score: 40.0
  SOUL_SAND:
    limit: 10000
  SPONGE:
    score: 50.0
    limit: 20
  SPRUCE_DOOR:
    score: 20.0
  SPRUCE_FENCE:
    score: 17.5
    diminishingReturns: 5000
  SPRUCE_FENCE_GATE:
    score: 40.0
    diminishingReturns: 100
  SPRUCE_STAIRS:
    score: 15.0
  SPRUCE_TRAPDOOR:
    score: 30.0
  SPRUCE_WOOD:
    additionalBlocks:
      - STRIPPED_SPRUCE_WOOD
    diminishingReturns: 10000
  SPRUCE_WOOD_STAIRS:
    score: 15.0
  STAINED_CLAY:
    score: 50.0
  STANDING_BANNER:
    score: 20.0
    diminishingReturns: 20
  STONE:
    diminishingReturns: 10000
  STONE_BRICK_SLAB:
    score: 7.0
    diminishingReturns: 10000
  STONE_PRESSURE_PLATE:
    score: 0.0
  STONE_SLAB:
    score: 5.0
    diminishingReturns: 10000
  SUGAR_CANE_BLOCK:
    score: 0.0
  TERRACOTTA:
    additionalBlocks:
      - BLACK_TERRACOTTA
      - BLUE_TERRACOTTA
      - BROWN_TERRACOTTA
      - CYAN_TERRACOTTA
      - GRAY_TERRACOTTA
      - GREEN_TERRACOTTA
      - LIGHT_BLUE_TERRACOTTA
      - LIGHT_GRAY_TERRACOTTA
      - LIME_TERRACOTTA
      - MAGENTA_TERRACOTTA
      - ORANGE_TERRACOTTA
      - PINK_TERRACOTTA
      - PURPLE_TERRACOTTA
      - RED_TERRACOTTA
      - WHITE_TERRACOTTA
      - YELLOW_TERRACOTTA
    score: 20.0
  TNT:
    score: 80.0
  TRAPPED_CHEST:
    score: 20.0
  VINE:
    limit: 25
  WALL_BANNER:
    score: 20.0
    diminishingReturns: 20
  WARPED_DOOR:
    score: 20.0
  WARPED_STAIRS:
    score: 15.0
  WARPED_TRAPDOOR:
    score: 30.0
  WATER:
    score: 0.0
  WEB:
    score: 20.0
  WET_SPONGE:
    score: 50.0
  WHITE_BED:
    additionalBlocks:
      - BLACK_BED
      - BLUE_BED
      - BROWN_BED
      - CYAN_BED
      - GRAY_BED
      - GREEN_BED
      - LIGHT_BLUE_BED
      - LIGHT_GRAY_BED
      - LIME_BED
      - MAGENTA_BED
      - ORANGE_BED
      - PINK_BED
      - PURPLE_BED
      - RED_BED
      - YELLOW_BED
    score: 1000.0
    limit: 1
  WHITE_STAINED_GLASS:
    additionalBlocks:
      - BLACK_STAINED_GLASS
      - BLUE_STAINED_GLASS
      - BROWN_STAINED_GLASS
      - CYAN_STAINED_GLASS
      - GRAY_STAINED_GLASS
      - GREEN_STAINED_GLASS
      - LIGHT_BLUE_STAINED_GLASS
      - LIGHT_GRAY_STAINED_GLASS
      - LIME_STAINED_GLASS
      - MAGENTA_STAINED_GLASS
      - ORANGE_STAINED_GLASS
      - PINK_STAINED_GLASS
      - PURPLE_STAINED_GLASS
      - RED_STAINED_GLASS
      - YELLOW_STAINED_GLASS
    score: 25.0
  WHITE_STAINED_GLASS_PANE:
    additionalBlocks:
      - BLACK_STAINED_GLASS_PANE
      - BLUE_STAINED_GLASS_PANE
      - BROWN_STAINED_GLASS_PANE
      - CYAN_STAINED_GLASS_PANE
      - GRAY_STAINED_GLASS_PANE
      - GREEN_STAINED_GLASS_PANE
      - LIGHT_BLUE_STAINED_GLASS_PANE
      - LIGHT_GRAY_STAINED_GLASS_PANE
      - LIME_STAINED_GLASS_PANE
      - MAGENTA_STAINED_GLASS_PANE
      - ORANGE_STAINED_GLASS_PANE
      - PINK_STAINED_GLASS_PANE
      - PURPLE_STAINED_GLASS_PANE
      - RED_STAINED_GLASS_PANE
      - YELLOW_STAINED_GLASS_PANE
    score: 10.0
  WHITE_WOOL:
    additionalBlocks:
      - BLACK_WOOL
      - BLUE_WOOL
      - BROWN_WOOL
      - CYAN_WOOL
      - GRAY_WOOL
      - GREEN_WOOL
      - LIGHT_BLUE_WOOL
      - LIGHT_GRAY_WOOL
      - LIME_WOOL
      - MAGENTA_WOOL
      - ORANGE_WOOL
      - PINK_WOOL
      - PURPLE_WOOL
      - RED_WOOL
      - YELLOW_WOOL
    score: 50.0
    diminishingReturns: 64
  WHITE_GLAZED_TERRACOTTA:
    additionalBlocks:
      - BLACK_GLAZED_TERRACOTTA
      - BLUE_GLAZED_TERRACOTTA
      - BROWN_GLAZED_TERRACOTTA
      - CYAN_GLAZED_TERRACOTTA
      - GRAY_GLAZED_TERRACOTTA
      - GREEN_GLAZED_TERRACOTTA
      - LIGHT_BLUE_GLAZED_TERRACOTTA
      - LIGHT_GRAY_GLAZED_TERRACOTTA
      - LIME_GLAZED_TERRACOTTA
      - MAGENTA_GLAZED_TERRACOTTA
      - ORANGE_GLAZED_TERRACOTTA
      - PINK_GLAZED_TERRACOTTA
      - PURPLE_GLAZED_TERRACOTTA
      - RED_GLAZED_TERRACOTTA
      - YELLOW_GLAZED_TERRACOTTA
    score: 20.0
  WITHER_SKELETON_SKULL:
    additionalBlocks:
      - WITHER_SKELETON_WALL_SKULL
    score: 1000.0
  YELLOW_FLOWER:
    diminishingReturns: 100
  ZOMBIE_HEAD:
    additionalBlocks:
      - ZOMBIE_WALL_HEAD
    score: 1000.0
version: 101
