name: Maven build

on:
  push:
    branches: [ gh-actions ]
  pull_request:
    branches: [ gh-actions ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
          git submodule update --init --recursive
      - name: Generate additional language files
        run: |
          cd uSkyBlock-Core/src/main/po && perl en2pirate.pl && cd -
          cd uSkyBlock-Core/src/main/po && perl en2kitteh.pl && cd -
      - name: JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -nsu -Pi18n clean deploy
